name: exam_app_offline
description: Offline-first exam application for students.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.0
  wakelock_plus: ^1.1.0
  share_plus: ^7.0.0 # Added for Manual Export
  permission_handler: ^11.0.0 # For storage permission if needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
